#' Makes PWM from differential abundunce data
#' 
#' The function extracts information for a selected enzyme, selected construct 
#' and selected kmer-lengthfrom a list of differential abundunce 
#' data generated by \code{\link{GetKmerDE}}. It creates a matrix, in which 
#' every row
#' corresponds to different kmer sequence (4^smallestUnit rows) and every column
#' corresponds to different starting position within a construct.
#' 
#' @param DEresults Output of "GetKmerDE"
#' @param enzyme_source Enzyme of interest
#' @param constr Construct of interest
#' @param smallestUnit Length of a kmer (1 = single nucleotide; 2 = dinucleotide, ...)
#' @return Matrix with log2FC associated with a given kmer at a given position for a given enzyme
#' @author Lukasz Jan Kielpinski
#' @seealso \code{\link{GetKmerDE}}
#' @export enrichmentMatrix

enrichmentMatrix <- function(DEresults, enzyme_source, constr, smallestUnit = 1){
  insertLength <- length(DEresults[[enzyme_source]][[constr]][[smallestUnit]])
  fc_results  <- matrix(nrow = 4**smallestUnit, ncol = insertLength)
  
  for(i in 1:insertLength){
    fc_results[,i] <- DEresults[[enzyme_source]][[constr]][[smallestUnit]][[i]][["logFC"]]
  }
  
  rownames(fc_results) <- makeAllKmers(smallestUnit)
  fc_results
}
